services:
  scheduler:
    image: mcuadros/ofelia:latest
    container_name: backup-scheduler
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - proxy
    labels:
      ofelia.enabled: "true"
      # Run every day at 03:00:00 (second minute hour day month weekday)
      ofelia.job-run.traefik-backup-task.schedule: "0 0 3 * * *"
      # Tell Ofelia to start the container by name
      ofelia.job-run.traefik-backup-task.container: "traefik-backup"
      # Run every day at 03:00:00 (second minute hour day month weekday)
      ofelia.job-run.evcc-backup-task.schedule: "0 * * * * *"
      # Tell Ofelia to start the container by name
      ofelia.job-run.evcc-backup-task.container: "evcc_2"

      
networks:
  proxy:
    external: true
